### ISSUE TITLE
Not working with ZTE Axon 7 B07 Marshmallow firmware

### ISSUE THREAD

**Issue by AnonVendetta** [NHellFire/android-qfil-unsparse#1]
I own the device listed in the title, and I'm attempting to work with the following file:

https://build.nethunter.com/misc/axon7/314740B24_MR79ZTE_A2017V1.0.0B07.zip

I ran a Linux Mint ISO in a virtual machine, installed a few prerequisites, then installed your repo with pip. Afterwards I unpacked the firmware, cd'ed to the firmware directory, and ran qfil-unsparse with no parameters.....nothing happens. No new file is generated, and all files remain the same size. The files I'm attempting to convert are:

cache.img
userdata.img
system.img (specified in a separate rawprogram xml, but not in rawprogram0.xml)

I have also tried running your tool as root, same results. I'm certain that the file I've linked to is a firmware meant to be flashed with QFIL.

I've also noticed that no partitions are listed when running with the -l parameter.

Can you look into this? Thanks!

**Comment by Phoenix09** [comment]
cache.img is 8k of nothing
userdata.img is 8k of nothing
system.img is an Android sparse image which needs to be converted using `simg2img`, not this tool

Yes that is a QFIL image, but none of the partitions are QFIL sparse images so this tool isn't needed.

**Comment by AnonVendetta** [comment]
I don't own this device anymore, and quite frankly, a response 8 months later really isn't (practically speaking) very useful.
